### ISSUE TITLE
`symbol lookup error` when trying to attach or download file

### ISSUE THREAD

**Issue by salim-b** [snapcrafters/signal-desktop#32]
When I try to send a file (i.e. click on the <kbd>+</kbd>) or to download a file attachment (i.e. click on the <kbd>⤓</kbd>), signal-desktop crashes with the following message:

```
/snap/signal-desktop/318/opt/Signal/signal-desktop --use-tray-icon --no-sandbox: symbol lookup error: /snap/signal-desktop/318/gnome-platform/usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: cairo_xlib_surface_create
```

May be related to https://github.com/signalapp/Signal-Desktop/issues/4061

I'm on Ubuntu 20.04.

**Comment by kr4ut** [comment]
Must confirm this with 318 on focal.
Upstream points to the Snap maintainers:
https://github.com/signalapp/Signal-Desktop/issues/3619

**Comment by popey** [comment]
Sorry about this. Revision 320 fixes this.

**Comment by salim-b** [comment]
> Revision 320 fixes this.

Thanks, I can confirm that.

Just out of curiosity, where can I see the change that fixed this? The last commit in this repo (master) is from May 15, 2020 – one day before I opened this issue... I'm not familiar with Snap deployment, but does that mean, the [Snap](https://snapcraft.io/signal-desktop) and this repo are not necessarily in sync?

**Comment by popey** [comment]
@salim-b Yeah, we did a quick ninja build out of channel from the repo to get the build unbroken. Pull requests followed after.

**Comment by salim-b** [comment]
> Yeah, we did a quick ninja build out of channel from the repo to get the build unbroken. Pull requests followed after.

I see. Does that mean there's no way for an "outsider" (like me) to see the actual source code a specific Snap package (in a specific channel) was built from?

**Comment by popey** [comment]
It's not built from source, we ingest the deb.

**Comment by salim-b** [comment]
> It's not built from source, we ingest the deb.

I figured that out. But the [changes that fixed this issue](https://github.com/snapcrafters/signal-desktop/compare/master@%7B2020-05-16%7D...master) weren't done in the DEB but in the `snap/snapcraft.yaml` file of this repo. So, by "actual source code" of the Snap I mean the state of this YAML file – and thus my question still holds. :slightly_smiling_face:

**Comment by popey** [comment]
I've triggered a new build, which uses the snapcraft.yaml in this repo, which should resolve the issue and bring both into alignment.

**Comment by salim-b** [comment]
I can't quite follow.

> I've triggered a new build, which uses the snapcraft.yaml in this repo

You triggered the build _yesterday_ but the changes were only added to this repo _today_ as you already [pointed out](https://github.com/snapcrafters/signal-desktop/issues/32#issuecomment-630676910). So it did _not_ use the `snapcraft.yaml` from this repo. What did I miss?

And related to this: Is there a standardized (i.e. direct) way to figure out the `snapcraft.yaml` a specific Snap package was built from? I can't see any such link or the like on the [snapcraft page](https://snapcraft.io/signal-desktop) (only _Contact Snapcrafters_ which links to this very repo).

**Comment by popey** [comment]
320 was built using the same yaml which is there right now, as was 321. The only difference is 320 was built before the change landed. 

If a snap is built in launchpad, it will typically *contain* the snapcraft.yaml and a manifest.yaml which allow the user to see what built it.

**Comment by salim-b** [comment]
> 320 was built using the same yaml which is there right now, as was 321. The only difference is 320 was built before the change landed.

I have no reason not to believe you and I didn't mean to suggest rev 320, 321 (or any other rev) were dubious! My question was more of a principle nature.

I just dared to google my integrity/transparency concerns and [this thread](https://forum.snapcraft.io/t/snap-build-transparency-and-trust/13261/) as well as [this one](https://forum.snapcraft.io/t/lack-of-package-provenance-is-a-security-concern/16316/) suggest that there's _a lot_ left to do in snap-world to really become a universal _and trustworthy_ source of Linux apps. :confused:
Actually, I'm a bit disenchanted with snap/snapcraft now. The complete lack of problem awareness in some (mostly @chipaca's) answers is frightening! 🤯

> If a snap is built in launchpad, it will typically contain the snapcraft.yaml and a manifest.yaml which allow the user to see what built it.

Ok. How can I see if a snap was "built in launchpad"?

In that regard, @galgalesh [wrote in the second thread linked above](https://forum.snapcraft.io/t/lack-of-package-provenance-is-a-security-concern/16316/2):

> Snaps can optionally include their build manifest in the snap as the file `snap/manifest.yaml`. However, this file could be doctored and the snap tools do not tell you to look in that file.

and in [another one](https://forum.snapcraft.io/t/snap-build-transparency-and-trust/13261/34):

> However, **this does not improve trust in any way**. Thinking that it does is dangerous because it gives you a false sense of security. A malicious snap publisher can very easily create a malicious snap and include a different `snapcraft.yaml` file.

Anyway, @galgalesh also [writes](https://forum.snapcraft.io/t/lack-of-package-provenance-is-a-security-concern/16316/4):

> To be clear, snaps _support_ transparent and reproducible builds, it just doesn’t _require_ them at any stage. Creating a reproducible snap package shouldn’t be much harder than creating a reproducible deb package.

@popey Any plans on making `signal-desktop` a _reproducible snap package_? The `snapcraft.yaml` in this repo already looks reproducible, but obviously we can't be sure that it corresponds to the [snap package from the official snap store](https://snapcraft.io/signal-desktop). Anything planned on improving this situation?

**Comment by galgalesh** [comment]
I'm the person you quote. I'm sorry that I wasn't more clear in my post. I'm thinking I should write a thorough blogpost about this, given many people ask me the same question. Let me try to explain it again:

There is a difference between "a build you can trust" and "a reproducible build". The topic on the forum was talking about both and my comment tried to explain the difference between them.

When a snap includes the `manifest.yaml` and `snapcraft.yaml` files, users can audit and try to reproduce the snap. *Doing that audit* gives them trust. The signal snap includes these files, so you can do that audit. If you don't trust the snap, then rebuild it yourself using the provided source and see what files are different in the resulting snap. **If you want to trust the signal snap, download it, take the file `snap/snapcraft.yaml`, and rebuild the snap yourself.** You can already do this today, because this snap has complete *transparency*.

The quote of me that you put in bold says a general statement about _trust_ in **every** reproducible builds initiative in existence: "The _presence_ of the source of a package does not make the package more trustworthy. You gain trust by using the provided source to rebuild the package yourself and checking whether the package you get is the same as the original one."

The goal of reproducible builds is to make it as easy as possible _to do that check_. They do this by modifying the build system so that every time you compile the source, you get the exact same bit-for-bit package. Then the only thing you need to do is to rebuild the package yourself and check whether the two packages have the same hash.

So back to the quote in bold: some people in the thread were claiming that we could improve the trust of snap packages by forcing publishers to include the source and build manifests. My quote simply says that this is not true, because publishers can tamper with the sources.

However, since Signal includes its sources, you can see for yourself whether these sources have been tampered with: rebuild the signal package and see which files have changed. As explained in the previous thread; because `snapcraft` records the build timestamp, a bit-for-bit comparison of the two snap packages will always be different, so in order to see whether there has been tampered with the package, you will need to extract it and diff each file.

**Comment by chipaca** [comment]
I'm here for my daily cup of blissful unawareness.

**Comment by salim-b** [comment]
@galgalesh What I'm asking for is: Can't you ensure a snap is directly (and only) built from a specific GitHub (or GitLab, Gitea whatever) repo? So I only have to trust the Git* provider that what I see in the source (`snapcraft.yaml`) through the web view or Git client is equivalent to what the API returns to the Git* provider.
