### ISSUE TITLE
Crash on renaming log file

### ISSUE THREAD

**Issue by stuartlangridge** [snapcrafters/signal-desktop#35]
Signal desktop just exited with the following popup:

Unhandled Error

Error: EACCES: permission denied, rename '/home/aquarius/snap/signal-desktop/320/.config/Signal/logs/log.log.1' -> '/home/aquarius/snap/signal-desktop/320/.config/Signal/logs/log.log.2'

**Comment by hackel** [comment]
Still seeing this exact same issue.  I believe it happens whenever a new version is installed and made active while the previous version of Signal is still running.  After receiving the error and closing Signal, restarting it (on the new version) worked fine, though my preferences and archived conversations seemed to be erased.

signal-desktop  1.35.1 2020-09-04
snapd   2.45.3.1

**Comment by galgalesh** [comment]
This is a bug on the `snapd` side. There is an experimental fix available. You can turn it on by running:

```bash
snap set core experimental.refresh-app-awareness=true
```

This will disable updates while the app is running.

More information here: https://snapcraft.io/blog/experimental-feature-snap-refresh-awareness-and-update-inhibition

Please reopen the issue if this bug is still present with that workaround turned on.
