### ISSUE TITLE
[Bug]: Always complaining that it needs a restart, complete data loss after re-install

### ISSUE THREAD

**Issue by jpicht** [snapcrafters/signal-desktop#66]
### What happened?

The app kept telling me it needs a restart to update or something to that effect.

Restarting did nothing.

After reinstalling all data is lost.

### What should have happened?

Notification does not re-appear every few minutes.

Data should have been there.

### Output of `snap info $snap_name`

```shell
name:      signal-desktop
summary:   Signal Desktop
publisher: Snapcrafters
store-url: https://snapcraft.io/signal-desktop
contact:   https://github.com/snapcrafters/signal-desktop/issues
license:   AGPL-3.0-only
description: |
  Private messaging from your desktop.
snap-id: r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
channels:
  latest/stable:    5.46.0 2022-06-22 (388) 180MB -
  latest/candidate: ↑                             
  latest/beta:      ↑                             
  latest/edge:      5.48.0 2022-07-02 (389) 180MB -
```

### Output of `snap connections $snap_name`

```shell
(not available anymore, I replaced snap with flatpak)
```

### Output of `snap version`

```shell
snap    2.56.2
snapd   2.56.2
series  16
ubuntu  22.04
kernel  5.16.8-051608-generic
```

**Comment by galgalesh** [comment]
We don't have access over this notification, it is sent by snapd. This notification appears each time `snapd` finds a new update for the snap. So the following might be happening:

* You run an outdated version of the snap
* and snapd for some reason constantly looks for updates.

Note that signal-desktop is released quite often, sometimes once every day.

If this problem persists, please file a bug at [snapd bugtracker](https://bugs.launchpad.net/snapd). I'm closing this issue for now since it's not an issue with this specific
