### ISSUE TITLE
[Bug]: "signal-desktop" not found

### ISSUE THREAD

**Issue by WillAyd** [snapcrafters/signal-desktop#70]
### What happened?

When trying to install signal via snap I am getting `"signal-desktop" not found`. It also appears like the link to the snap no longer works?

https://snapcraft.io/signal-desktop

### What should have happened?

App should have installed

### Output of `snap info $snap_name`

```shell
error: no snap found for "signal-desktop"
```

### Output of `snap connections $snap_name`

```shell
error: snap "signal-desktop" not found
```

### Output of `snap version`

```shell
snap    2.57.2
snapd   2.57.2
series  16
ubuntu  22.04
kernel  5.15.0-50-generic
```

**Comment by galgalesh** [comment]
I don't know more than you do, I apologise. The snap is currently in review, I don't know for what and I don't know how long this will take. I'll keep you updated once I know more.

**Comment by boistordu** [comment]
any news about it? it has been 10 days.... seems a long time afor a problem of review....

**Comment by galgalesh** [comment]
I haven't received a single update yet. I'm not too pleased with this. This is no way to treat maintainers, imo.

**Comment by fujimotos** [comment]
JFYI, there is a related thread on forum.snapcraft.io:

https://forum.snapcraft.io/t/what-happened-to-signal-desktop/32119

and it got a reply from the policy team:

> I understand the sudden move of signal-desktop can be disruptive for people wishing to install this package. Just to confirm the reason for the absence - Snap Store administrators had to remove the snap in accordance with our policies. We hope to have it back shortly.

The impact to the existing users (i.e. whoever installed signal-desktop previously):

> There is NO impact to existing users. If you have the application/snap installed, you can continue to use it confidently.

It seems that the moderator team suddenly found signal-desktop unacceptable
for distribution on Snap store. I have no insight on their internal reasoning,
but it could be signal being subject to export control?

**Comment by galgalesh** [comment]
Wow, thanks for linking this!

It's mind-boggling that they provide more information to a random person asking about it on the forum than to the actual maintainers of the package!

**Comment by qtlin** [comment]
Just out of curiosity, is there flatpack variant by any chance?

**Comment by dennisTGC** [comment]
So, I went down the rabbit hole because signal gave the message the client was too old, the snap was installed, but could not be refreshed, etc..

> There is NO impact to existing users. If you have the application/snap installed, you can continue to use it confidently.

So this is not true, it can't be used anymore. I installed the apt package, but this is a bad user experience..

**Comment by DL6ER** [comment]
I just want to mention that this one-sided action of the `snap` does *not* mean you cannot use `signal-desktop`. Consider building the `snap` locally instead of pulling it from the store, this is very easy as follows:

```
sudo snap install --classic snapcraft
git clone https://github.com/snapcrafters/signal-desktop.git
cd signal-desktop
snapcraft
sudo snap install --devmode signal-desktop_5.62.0_amd64.snap
```
(agree to install `multipass` if asked to)

Afterwards, you can start is as usual using `signal-desktop`

It takes about ten minutes on an arbitrary computer.

**Comment by pabl0** [comment]
> Just out of curiosity, is there flatpack variant by any chance?

There is indeed, https://github.com/flathub/org.signal.Signal

**Comment by lachesis** [comment]
You can also just install the Signal deb directly from [their download page](https://signal.org/download), signed by Signal instead of Canonical (for the Snap) or a random third party (for the flatpack).

**Comment by galgalesh** [comment]
Update: This is due to a DMCA takedown request coming from people representing Signal. Canonical is currently working with Signal to resolve this issue.

There was an initial communication breakdown between me and Canonical due to how the Snapcrafters publisher is structured. Canonical is changing their procedures to make sure this communication breakdown doesn't happen in the future anymore.

I've suggested to Canonical to be more transparent with DMCA takedown requests, similar to how GitHub does it. Last I heard, they were discussing this internally.

**Comment by lanz** [comment]
Sending DMCA takedowns doesn't help with building trust with the open source community, and Signal is in no position currently to erode trust even further.

**Comment by diddledani** [comment]
This isn't the place to discuss the merits of DMCA and how that relates to Signal. Please use Reddit or elsewhere for such discussions.

**Comment by paride** [comment]
@galgalesh this is great news. Was any special agreement needed to allow you to package signal-desktop? This can be useful information for other downstream packaging efforts (e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842943). Thanks!

**Comment by galgalesh** [comment]
@paride the issue blew up on Hacker News and suddenly there wasn't an issue anymore from Signal's side. I didn't change anything to the snap package.

If I hear more info from Canonical's legal department, I will put it here. But at the moment it seems "throw a big stink" is the best way to get Signal's approval.

**Comment by pabl0** [comment]
So, if I understand correctly, this snap is generated in similar fashion like the Flatpak distributed in Flathub? I.e. you just use the deb package from updates.signal.org and do not compile from source? I've not heard about the Flatpak effort facing any legal problems?

**Comment by diddledani** [comment]
@pabl0 yea you are correct about how we create the snap. It is very similar to how flatpak does it (I don't know who was first there, but we're both doing it the same way)

**Comment by ksaadDE** [comment]
> @paride the issue blew up on Hacker News and suddenly there wasn't an issue anymore from Signal's side. I didn't change anything to the snap package.
> 
> If I hear more info from Canonical's legal department, I will put it here. But at the moment it seems "make a big stink" is the best way to get Signal's approval.

Any news why they took it down (via DCMA bs) ? In the Github Repo of Signal Desktop they stated that they just don't like snaps etc. So maybe it is a internal company policy at Signal Org?

Tbh I don't understand their logic, but it's the same thing like with the security vulnerability I had reported to them a time ago...  They just refused to fix it because.. well nobody knows LOL 

We created some rant about that too, but somehow it didn't catch that much attention. Despite the vulnerability is serious. 

Keep in mind that you had all support from the Community. We complained in your case at all possible locations, on Reddit, on Twitter, on Facebook, on several Discord communities (hacking, dev etc) and all other platforms, where intelligent people do tech. The Signal Org had no chance other than to follow the public opinion.

To our Microsoft friends in this Issue.. It IS the right place to talk about such problems HERE. Not somewhere else. However, I agree to the partial argument, that we shouldn't rant here - someone says a thing, put a emoji reaction to it, and it's fine - no need for more posts about that.

Dev Love from Germany to you all! 

Regards
