### ISSUE TITLE
Device link lost after upgrade due to version specific config

### ISSUE THREAD

**Issue by flyingflo** [snapcrafters/signal-desktop#8]
This is probably related to #1.

After an upgrade in ~/snap/signal-desktop a new directory is created for the new version. In this case it is the recent update from 114 to 115. The version specific directory contains the device link. Thus, signal breaks after an upgrade because the device binding is gone.

Shouldn't the config be placed in the common folder?

```
% ls -a 114
./  ../  .config/  .last_revision  .local/  .themes@
% ls -a 115   
./  ../  .config/  .last_revision  .local/  .themes@
% ls -a common
./  ../  .cache/
```

**Comment by flyingflo** [comment]
Probably the copy-over at the upgrade didn't work..

**Comment by flyingflo** [comment]
It looks like this is the effect of a refresh/update while the app is running..

**Comment by popey** [comment]
Thanks for the report. This can indeed happen while updates are in flight.

We have an experimental feature, designed to mitigate this issue. It's blogged about at https://ubuntu.com/blog/experimental-feature-snap-refresh-awareness-and-update-inhibition
This issue is indeed a snap-related one, and we're working to get that feature landed by default as soon as we can. For now, this is the workaround.

`snap set core experimental.refresh-app-awareness=true`

This will prevent the app updating while it's running.

**Comment by galgalesh** [comment]
Note: the upstream issue in snapd is tracked here: https://bugs.launchpad.net/snapd/+bug/1616650
